export const REQUEST_CONTACT_FETCHED = 'general.REQUEST_CONTACT_FETCHED';
export const CONTACT_FORMAT_FETCHED = 'general.CONTACT_FORMAT_FETCHED';
export const REQUEST_EVENT_FETCHED = 'general.REQUEST_EVENT_FETCHED';
export const EVENT_FORMAT_FETCHED = 'general.EVENT_FORMAT_FETCHED';
