export const MENU_CHALLENGE_FETCHED = 'events.MENU_CHALLENGE_FETCHED';
export const WINNER_CHALLENGE_FETCHED = 'events.WINNER_CHALLENGE_FETCHED';
export const CHALLENGE_DETAIL_FETCHED = 'events.CHALLENGE_DETAIL_FETCHED';
