export const UPCOMING_EVENTS_FETCHED = 'events.UPCOMING_EVENTS_FETCHED';
export const LIVE_EVENTS_FETCHED = 'events.LIVE_EVENTS_FETCHED';
export const RESULT_EVENTS_FETCHED = 'events.RESULT_EVENTS_FETCHED';
export const PERSON_EVENTS_FETCHED = 'events.PERSON_EVENTS_FETCHED';
export const FRIEND_EVENTS_FETCHED = 'events.FRIEND_EVENTS_FETCHED';

