export const LOGIN_AUTH_FETCHED = 'auth.LOGIN_AUTH_FETCHED';
export const RESET_PWD_FETCHED = 'auth.RESET_PWD_FETCHED';
export const RESETPWD_FORMAT_FETCHED = 'general.RESETPWD_FORMAT_FETCHED';
export const SEND_PWD_FETCHED = 'auth.SEND_PWD_FETCHED';
export const SENDPWD_FORMAT_FETCHED = 'general.SENDPWD_FORMAT_FETCHED';